// Generated by Wrangler on Thu Jul 18 2024 21:28:00 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	BASE_URL: string;
	IMG_PREFIX: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	RESEND_KEY: string;
	RESEND_AUDIENCE_ID: string;
	MAPBOX_TOKEN: string;
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_SITE_KEY: string;
	BARK_SERVER: string;
}
