// Generated by Wrangler on Thu Jul 18 2024 21:28:00 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	RESEND_KEY: string;
	RESEND_AUDIENCE_ID: string;
}
